### ISSUE TITLE
A small question.

### ISSUE THREAD

**Issue by CatzTimes** [M10327/SilverBarricadeStructureTools#1]
UseUI = true, UiId = 28001 in SilverBarricadeStructureTools/Config.cs, what is the creative workshop link of this UI?

**Comment by M10327** [comment]
There's no dedicated workshop for it. I bundled the UI in with the mod that I put all my server content in. [Link](https://steamcommunity.com/sharedfiles/filedetails/?id=2942670028). I don't recommend using that because it has tons of edited spawn tables and other stuff. You'll need to make your own UI for that if you wanna use it.

**Comment by CatzTimes** [comment]
<BuildableRepairDelay Enabled="true">
    <RepairDelaySeconds>10</RepairDelaySeconds>
    <UseChat>false</UseChat>
    <UseUI>true</UseUI>
    <UiId>28001</UiId>
  </BuildableRepairDelay>
  Hello, I don’t quite understand what function this is and what it is used for?

**Comment by M10327** [comment]
Im not sure what youre asking about

**Comment by CatzTimes** [comment]
SilverBarricadeStructureTools >> Common
Position: (-1414.35, 118.83, 1455.80)
Angles: 0, 262.8241, 0
Owner: 76561198224113800
Group: 103582791469689554
SilverBarricadeStructureTools >> Navmesh ID 11

I read this log the day after tomorrow, and then I discovered that after the player prevents the zombie machine, the zombie machine in the backpack will not be consumed.

**Comment by M10327** [comment]
what?
